source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'FilterSortTest' do

    pod 'Alamofire', '~> 3.0'
    pod 'SDWebImage', '~> 3.8'
    pod 'SlideMenuControllerSwift', '~> 2.2'
    pod 'SVProgressHUD', '~> 2.0'
    pod 'IBMMobileFirstPlatformFoundation', '~> 8.0'
		
end

target 'FilterSortTestTests' do

end

target 'FilterSortTestUITests' do

end

	
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == "IBMMobileFirstPlatformFoundation"
                config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
            end
        end
    end
end
	
